### ISSUE TITLE
Musical works paging behaving incorrectly

### ISSUE THREAD

**Issue by farski** [PRX/cms.prx.org#108]
Eg: https://cms.prx.org/api/v1/stories/36935/musical_works.json?page=2

I would expect the `next` `_link` to be page 3, but currently it's returning page 2

**Comment by kookster** [comment]
Yeah, def CMS bug; I'll get on it.

- Andrew

**Comment by kookster** [comment]
Looks like a caching issue - if I add a `zoom` param, it misses the cache, and returns the correct response.

**Comment by kookster** [comment]
PR waiting for review.
