### ISSUE TITLE
Process audio after upload - validate, copy, create derivatives

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#122]
Making this one ticket for all processing as fixer will do the heavy lifting.

Compliments other tickets for the www.

**Comment by cavis** [comment]
Covered by #146 - which will validate/copy, but currently doesn't create derivative files.  As that's out-of-scope for publish-1.0, which only cares about non-broadcast files.

**Comment by kookster** [comment]
closing this for now, when we know what we are doing for transcode, will open specific tix for that
