### ISSUE TITLE
Tags over-cached on update requests

### ISSUE THREAD

**Issue by cavis** [PRX/cms.prx.org#135]
Making a PUT request to a story with `{"tags":["Foobar"]}` doesn't seem to bust the cache in production.  So subsequent GET requests will come back with the un-altered tags, until the cache expires some minutes later.

Should re-check this after @kookster's latest PR, and investigate if that doesn't fix it.

**Comment by cavis** [comment]
I'm also noting that altering tags on a story doesn't change the `updatedAt`.  From an API-usage standpoint, that's a bit awkward, since tags are returned as a top-level story attribute.

**Comment by kookster** [comment]
ok, that at least explains it - that shouldn't happen, any update to the model should update the `pieces.updated_at`
