### ISSUE TITLE
Update individual-account memberships

### ISSUE THREAD

**Issue by cavis** [PRX/cms.prx.org#153]
v3 now gives users a membership into their default/individual account.

- [x] Simplify accounts/networks/stories relations in `user.rb`, which no longer need the "OR individual-account-id"
- [x] Update `user.rb` to also create a default/individual account + membership for new users (though I'm not sure we allow creating users via CMS just yet).

**Comment by cavis** [comment]
Related: seeing many users without individual accounts in production, which causes a 500 given the current code (looks for a user's `individual_account.id`) - https://cms.prx.org/api/v1/users/239444

Also distressing - there are some users with multiple individual accounts (though much fewer).

```
mysql> select count(*) from users where id not in (select opener_id from accounts where type = 'IndividualAccount');
+----------+
| count(*) |
+----------+
|    20806 |
+----------+
1 row in set (0.34 sec)

mysql> select count(*) from (select u.id, count(*) as count from users u join accounts a on (u.id = a.opener_id) where a.type = 'IndividualAccount' group by u.id) t where count > 1;
+----------+
| count(*) |
+----------+
|      224 |
+----------+
1 row in set (0.85 sec)
```

@kookster is that the sort of thing we need to clean up?

**Comment by kookster** [comment]
I have looked at this  - it is a bit smaller problem than that:
```
mysql> select count(a.id) as ac, a.opener_id from accounts a join users u on (u.id = a.opener_id) where a.type = 'IndividualAccount' and a.deleted_at is null  group by a.opener_id having ac > 1;
+----+-----------+
| ac | opener_id |
+----+-----------+
|  4 |     70199 | 
|  5 |     70236 | 
|  2 |     70339 | 
|  2 |     70473 | 
|  2 |     72162 | 
|  3 |     72163 | 
|  4 |     72751 | 
|  2 |     78370 | 
+----+-----------+
8 rows in set (4.09 sec)

```

**Comment by kookster** [comment]
data is fixed, forever!
```

mysql> select count(a.id) as ac, a.opener_id from accounts a join users u on (u.id = a.opener_id) where a.type = 'IndividualAccount' and a.deleted_at is null  group by a.opener_id having ac > 1;
Empty set (3.46 sec)
```
