### ISSUE TITLE
Filtering series by text in name and description

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#156]

**Comment by kookster** [comment]
@cavis I'm trying to decide if this is its own param, like `page`, `per` or `zoom`, or a filter param like `v4`, or `highlighted`.

My thought is probably a filter, where top level params affect the result set size and resolution, but the filter params affect which records ought to be included - is that how you see it as well?

**Comment by cavis** [comment]
Yeah - continuing to add them to the `?filters` query param makes the responsibilities clear.  And at some point, I was thinking we could reveal the valid filters for a resource via the API links themselves.  By having the representer interrogate the controller, or something.

**Comment by kookster** [comment]
yeah, could add them in some kind of response, OPTIONS maybe, or link attributes in the HAL resource?
