### ISSUE TITLE
What should producers be able to see about ad serving?

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#179]
Which ones have been downloaded in podcasts, or in players, which ones are being played or skipped?

**Comment by sandikbarr** [comment]
Ad Impressions would be an easier stat to get right now than precisely _which_ ads were delivered

**Comment by kookster** [comment]
Issue moved to [PRX/chart.prx.org #4](https://github.com/PRX/chart.prx.org/issues/4) via [**ZenHub**](https://www.zenhub.com/)
