### ISSUE TITLE
Audio-version to use with podcast

### ISSUE THREAD

**Issue by cavis** [PRX/cms.prx.org#192]
Indicate which audio version is associated with the podcast distribution.

**Comment by kookster** [comment]
#211 implements

**Comment by sandikbarr** [comment]
Seems I need this for https://github.com/PRX/publish.prx.org/issues/155. I don't have a way of differentiating which story audio version to default to the series podcast distribution explicit value.

**Comment by sandikbarr** [comment]
Seems we need it for https://github.com/PRX/publish.prx.org/issues/172 too
