### ISSUE TITLE
Multiple series images

### ISSUE THREAD

**Issue by cavis** [PRX/cms.prx.org#193]
Need both the iTunes large and small image for feed.  Either allow multiple images to be associated with the Series, or somehow set that on the podcast Distribution.

**Comment by sandikbarr** [comment]
What's the iTunes small image? This is what I can find on image requirements:
https://help.apple.com/itc/podcasts_connect/#/itc1723472cb
Podcast feeds contain artwork that is a minimum size of 1400 x 1400 pixels and a maximum size of 3000 x 3000 pixels, 72 dpi, in JPEG or PNG format with appropriate file extensions (.jpg, .png), and in the RGB colorspace.

**Comment by cavis** [comment]
I may have worded that poorly.  The small image is the plain ol' `<image>` in the RSS spec, which has a pretty small max width/height.  (The spec says 144x400, but most of our feeds seem to be 300x300).  Publish is currently not setting this one.

The itunes-image is the one Publish currently uploads.

**Comment by kookster** [comment]
I can add this, also need a way to distinguish which image is used for a given purpose.
We could overload a label field for this, or add some kind of use or purpose attribute. hmm.

**Comment by kookster** [comment]
#208
