### ISSUE TITLE
500 instead of 404 for account/image

### ISSUE THREAD

**Issue by cavis** [PRX/cms.prx.org#200]
When you log into beta.prx.org as a user without an avatar, it makes a GET request directly to the account image (i think Publish just uses the embedded image).

When this image doesn't exist, CMS is returning a 500 "undefined method 'updated_at' for nil:NilClass" (see `https://cms.prx.org/api/v1/accounts/208390/image`).  At a glance, this appears to be coming out of `hal_api-rails`, in the `show_cache_path` method.  But more likely, we should be returning a 404 from CMS long before getting to the cache path.

**Comment by kookster** [comment]
fixed.
