### ISSUE TITLE
Handle null tags in importer

### ISSUE THREAD

**Issue by cavis** [PRX/cms.prx.org#271]
Seeing this error trying to import [this feed](http://bobreevesbrass.libsyn.com/rss):

```
  NoMethodError: undefined method 'uniq' for nil:NilClass
	from /app/app/models/story.rb:143:in 'tags='
```

Guessing we just need to handle the lack of categories on feed items.

**Comment by kookster** [comment]
@cavis this was OFFSHORE?

**Comment by cavis** [comment]
Fixed! Forever!
