### ISSUE TITLE
On import, populate feedburner link as the public url

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#275]
If the import, if we are importing a feedburner url, save the feedburner url as the public url link

Question - will this mess up the player or anything if this is not actually yet the public url, since on import the feedburner url is still pulling from some other feed, not this new one? @cavis @gcampo88

**Comment by gcampo88** [comment]
Hang on @kookster , which column do we want this to go through to? In feeder column terms: `url`, `source_url`, or `feed_burner_url` ? Right now the import does not set `feedburner_url`, just `path` -- should we set both `feedburner_url` and `url` to the feedburner url?

**Comment by kookster** [comment]
`url` is what I remember gets set as the public feed url in 'publish'.
that is the one to set.

We could also set feedburner_url if you are sure it is feedburner.
It serves one purpose - it is only used for pings. Maybe these two fields could/should be coalesced?
