### ISSUE TITLE
On import, set feeder owner and author name and email

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#277]
currently it is using the itunes:author tag, which has no email
look at the author tag as well

**Comment by kookster** [comment]
Hang on a sec - I just double-checked the feed b/c I was curious how this was looking, and the http://feeds.jeanchatzky.com/HerMoney podcast doesn't have an email address set for author - and it has no <author> tag at all. It has the itunes:author tag with a name only.

**Comment by kookster** [comment]
Maybe you're looking at the itunes:owner name and email tags?

**Comment by gcampo88** [comment]
Hmm, yeah -- I must have been looking at the itunes:owner bit, where there's an empty itunes:email tag, and confused that issue (from the feed) with the fact that in feeder the imported HerMoney podcast currently has no `author_email`. Currently, if the import only looks at `itunes_author` to set author, it will never set `author_email`, correct?

**Comment by gcampo88** [comment]
Looks like neither `owner_name` nor `owner_email` was set in Feeder when I imported HerMoney: 
```Ruby
    id: 158,
    title: "HerMoney with Jean Chatzky",
    managing_editor_name: "Jean Chatzky Her Money",
    author_name: "Jean Chatzky Her Money",
    owner_name: nil,
    owner_email: nil,
```

could it be because the import process tries to set `owners` and we only allow for one owner in feeder? (is there some case when there would be multiple <itunes:owner> tags in a feed?)
    `podcast_attributes[:owners] = Array(feed.itunes_owners).map do |o| ... `

**Comment by kookster** [comment]
Yeah, I just looked at the feeder API and it only supports a single owner, so it should be change just to send the first owner.

I'll update this ticket since that's the issue.

**Comment by gcampo88** [comment]
Hang on -- looks like Feeder API still expects an array of `owners` though, right? Even though it only allows one owner_name and owner_email per podcast.  
https://github.com/PRX/feeder.prx.org/blob/master/app/models/podcast.rb#L72 : 
```Ruby
  def owners=(os)
    owner = Array(os).first || {}
    self.owner_name = owner['name']
    self.owner_email = owner['email']
  end
```
Shall I open up a Feeder ticket to change that as well?

**Comment by gcampo88** [comment]
answering myself -- nope, that's just for stuff that comes in from Crier. stuff that comes in through API will go through feeder's Podcast Representer, which expects a singular owner.
