### ISSUE TITLE
On import, change the explicit value to 'explicit' or 'clean'

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#295]
Right now it copies in whatever the value is, which may be 'yes', 'no', etc.
But the publish UI expects 'Clean' or 'Explicit' to be saved as 'clean' or 'yes':
https://github.com/PRX/publish.prx.org/blob/master/src/app/series/directives/series-podcast.component.ts#L15

https://github.com/PRX/publish.prx.org/blob/master/src/app/shared/model/audio-version.model.ts#L93

itunes supports all these values: https://help.apple.com/itc/podcasts_connect/#/itcb54353390
> Yes | Explicit | True. If you specify yes, explicit, or true, indicating the presence of explicit content, the iTunes Store displays an Explicit parental advisory graphic for your podcast.
> 
> Clean | No | False. If you specify clean, no, or false, indicating that none of your podcast episodes contain explicit language or adult content, the iTunes Store displays a Clean parental advisory graphic for your podcast.

**Comment by gcampo88** [comment]
closed via #297
