### ISSUE TITLE
Select a template per episode

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#305]
Some shows will have more then one structure for their episodes, and we need a way to handle this.

Maybe you can decide to make a version of the media for the show with no template, or choose from more than one template used on a show.

1) This may be b/c they had structure for older episodes, then choose to use a new structure (maybe a single file for old, and the more complex structure for new)

2) It could also be b/c their feed includes longer episodes, such as a full hour of a b'cast program, mixed with shorter podcast only content (which could be an alternative template)

3) It could also be that sometimes there is just an odd episode, such as a video instead of the usual episode, and it is not going to be repeated, so perhaps no template is appropriate

**Comment by cavis** [comment]
I think we already have other tickets to cover this.  Can you think of any reason to keep this, @kookster?

**Comment by kookster** [comment]
no
