### ISSUE TITLE
Support season in cms for new iTunes tag

### ISSUE THREAD

**Issue by gcampo88** [PRX/cms.prx.org#319]
🎉 
http://podcasts.apple.com/resources/spec/ApplePodcastsSpecUpdatesiOS11.pdf 

other tickets for other apps, but for cms we will add a season identifier, like the episode identifier, as this is something common to the content whether it is a podcast or not

**Comment by kookster** [comment]
trimmed down to adding the `season_identifier`

**Comment by kookster** [comment]
I think it should enhance add_episode_to_feeder, as that is how the other cms and feeder attributes work, yes?

**Comment by gcampo88** [comment]
agreed

**Comment by gcampo88** [comment]
moving to Done in light of  https://github.com/PRX/prx.org/pull/311 and https://github.com/PRX/cms.prx.org/pull/346

once we verify in staging + deploy to prod, we can close
