### ISSUE TITLE
PublicAssetsController 404s

### ISSUE THREAD

**Issue by cavis** [PRX/cms.prx.org#337]
Not handling deleted public-assets correctly, which throws 500s to New Relic instead of 404s.

```
Couldn't find AudioFile with 'id'=1147716 [WHERE `audio_files`.`deleted_at` IS NULL]

    app/controllers/public_assets_controller.rb:  29:in `find_valid_asset'
    app/controllers/public_assets_controller.rb:   6:in `show'
```

This is very noisy, and makes it hard to monitor for actual errors.

**Comment by gcampo88** [comment]
moving to Done since #338 has merged, but not Closed yet since we'll need to deploy -> prod via Cap
