### ISSUE TITLE
Ongoing sync issues

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#386]
We have made changes to try to eliminate this, but the announcements of changes are still not always getting processed in feeder.

Best current understanding of why is that the messages have inexact updated at values - only good to the second, and that this is causing some update/publish messages to be processed out of order.

Ideas for solving:
 - Add millisecond resolution to updated at, esp. coming from central time at db server, perhaps with a trigger and additional column in the pieces table, update model to use both fields
 - Have the recipient of the announcement call the CMS API to get the latest info rather than rely on the data in the message
 - Create some "belt and suspenders" processing on publish to make sure the episode shows up in the feed w/i some period of time, then try to fix if it does not, then raise alerts

**Comment by debenedictis** [comment]
For reference, I think this is the most recent example: https://prx.zendesk.com/agent/tickets/97842

**Comment by gcampo88** [comment]
new most recent example: https://prx.zendesk.com/agent/tickets/98934
changing this to high!

**Comment by kookster** [comment]
belt & suspenders deployed and running.
adding a new ticket to feeder to hit the cms api instead of using the contents of the announce message for latest story and series data.

**Comment by kookster** [comment]
https://github.com/PRX/feeder.prx.org/issues/279
