### ISSUE TITLE
Import fails on emoji in feed

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#391]
mysql 5.0 can't handle 4 byte utf8 column type, so, need to keep these out for now.

Ideas:
https://github.com/maximeg/activecleaner/blob/master/lib/active_cleaner/utf8mb3_cleaner.rb#L38
https://stackoverflow.com/questions/16487697/how-to-remove-4-byte-utf-8-characters-in-ruby
https://gist.github.com/adamlwatson/9623703

**Comment by kookster** [comment]
(estimate of 2 b/c of time to research solutions)

**Comment by pkarman** [comment]
When I faced this issue before I converted the 4-byte characters into ASCII entity expressions: &#nnnnn; e.g. That's only if you care about preserving them.
