### ISSUE TITLE
Option to sort by _both_ published/released

### ISSUE THREAD

**Issue by cavis** [PRX/cms.prx.org#401]
Add a sort option for stories, so they can be sorted by whichever-isn't-null published_at and released_at (not one before the other).  This will put unpublished (but released_at is set) episodes into the correct order for Publish.

Will take something like `.order("COALESCE(published_at, released_at)")`

**Comment by pkarman** [comment]
@cavis something like?
```diff
diff --git a/app/models/story.rb b/app/models/story.rb
index 93f0255..159cf8b 100644
--- a/app/models/story.rb
+++ b/app/models/story.rb
@@ -92,6 +92,7 @@ class Story < BaseModel
   scope :unseries, -> { where('`series_id` IS NULL') }
   scope :v4, -> { where(app_version: PRX::APP_VERSION) }
   scope :network_visible, -> { where('`network_only_at` IS NULL') }
+  scope :published_released, -> { order("COALESCE(published_at, released_at)") }

   scope :series_visible, -> {
     joins('LEFT OUTER JOIN `series` ON `pieces`.`series_id` = `series`.`id`').
```

**Comment by cavis** [comment]
Yeah, it may not hurt to define it in the model.  But the controller is where you'll have to actually tie the query param into that, via the halapi-rails stuff (see `api/auth/stories_controller.rb`).  Hmm... I'm not clear how a scope would play with a multiple-order-by statement there.  May have to play around with it a bit.

**Comment by cavis** [comment]
In fact ... I'm guessing we want to scope this new `?sort=` under the auth-stories controller.  Since public stories always have `published_at != nil`.

The question is ... new sort param, or just hijack the current `?sorts=published_at desc`?  Maybe something new would be more explicit.

Also just to clarify ... I would expect this sorter to order `published_at = nil && released_at = nil` before everything else (same as that IS_NULL logic), and then order by `published_at || released_at`.

**Comment by pkarman** [comment]
I tend to lean toward re-using the current param name, unless introducing `released_at` into the sort order would break API consumer expectations?

e.g. if a story has `published_at = nil` and `released_at = Time.now` would you expect that to sort before or after `published_at = Time.now - 1` and `released_at = nil` ?

**Comment by cavis** [comment]
Hmm... yeah, maybe reusing wouldn't be all bad.  Currently, Publish is the only app using that authorized-stories endpoint.

And it seems to always ask for [both of those sorts](https://github.com/PRX/publish.prx.org/search?utf8=%E2%9C%93&q=sorts&type=) together: `?sorts=released_at: desc, published_at: desc`.  (Also... I didn't know you needed a `:` in that sorts string).

**Comment by cavis** [comment]
and per your example ... I'd expect to see them in the order you listed.  As if there was a `publish_or_released_at` field.

**Comment by pkarman** [comment]
what about the opposite? 

if a story has `published_at = nil` and `released_at = Time.now` would you expect that to sort before or after `published_at = Time.now + 1` and `released_at = nil` ?

that would sort like:
```
published_at [Time.now + 1]
published_at [nil]
```
which would be different than current sort?

**Comment by cavis** [comment]
So when trying to get the "most recent" stories in a series, I would expect:

```
# ?sorts=published_or_released_at desc
[
  {published_at: nil, released_at: nil},
  {published_at: 2018-02-22, released_at: nil},
  {published_at: nil, released_at: 2018-02-22},
  {published_at: 2018-02-22, released_at: nil},
  {published_at: 2018-02-18, released_at: nil},
  {published_at: nil, released_at: 2018-02-17},
  {published_at: nil, released_at: 2018-02-16},
  {published_at: 2018-02-15, released_at: nil},
]
```

In other words ... if there's a tie between published/released, the sort behavior is unspecified.

**Comment by pkarman** [comment]
I now think a new param is better. The `sorts` API param provides ad hoc sorting. This new logic is hardcoded on the server side. How about `coalesce_published_released=1` for a name?

**Comment by kookster** [comment]
I am concerned about adding a new param to the API for this very specific purpose - we already have sorting, is this new complexity justified?

**Comment by kookster** [comment]
so you're thinking to still sue some value for the `sorts` param, ok.

I think we should probably be setting released_at = published_at when we publish an episode...
that is logically what is happening.

Which makes me think sorting by `released_at` is essentially the same as coalesce between publish and released, and I don't think this needs a new param - I would just use released_at.

**Comment by kookster** [comment]
the difference then is sorting by `published_at` => sorted by current published time, vs `released_at` => when it will be (future released_at) or was published (released previously, subsequently unpublished) but may or may not be published at present.

**Comment by kookster** [comment]
h/t @gcampo88 - gigi and I ran into this with the moth, where we had old episodes we wanted to unpublish, but have them "remember" when they were published, and return to that value when re-published - she correctly figured out we could just set released_at = published_at before unpublishing, and it works as expected

**Comment by gcampo88** [comment]
coming into this late... `I think we should probably be setting released_at = published_at when we publish an episode... that is logically what is happening.` that seems reasonable to me! and yeah, would then mean we could just sort by release date.

**Comment by pkarman** [comment]
so something like?
```diff
diff --git a/app/models/story.rb b/app/models/story.rb
index c84745d..c341f86 100644
--- a/app/models/story.rb
+++ b/app/models/story.rb
@@ -215,6 +215,7 @@ class Story < BaseModel
       raise "Story #{id} is already published."
     else
       update_attributes!(published_at: (released_at || DateTime.now))
+      update_attributes!(released_at: published_at) unless released_at
     end
   end
```

**Comment by pkarman** [comment]
after slack discussion, we're leaving the data logic alone and adding the API `sort=coalesced:desc` param only. PR in #407

**Comment by pkarman** [comment]
I changed it to a virtual column `published_released_at` so that the sort direction can be toggled. Publish PR in https://github.com/PRX/publish.prx.org/pull/505
