### ISSUE TITLE
Text search errors on single quote

### ISSUE THREAD

**Issue by cavis** [PRX/cms.prx.org#422]
Request:

```
GET /api/v1/authorization/stories?page=1&per=12&zoom=prx%3Aimage,prx%3Aseries&filters=v4%2Ctext%3Dyou%27ve&sorts=published_at%3Adesc%2C%20updated_at%3Adesc
```

500 Error:

```
You have an error in your SQL syntax; check the manual that corresponds to your 
MySQL server version for the right syntax to use near 've%' OR `pieces`.`short_description` 
like '%you've%' OR `pieces`.`description` l' at line 1
```

**Comment by debenedictis** [comment]
@cavis Just asking on behalf of KERA...  When might this get assigned to a milestone?

**Comment by pkarman** [comment]
We are working on a solution that would solve this (and other problems) in #426

**Comment by debenedictis** [comment]
@cavis I noticed this ticket has no assignee and no milestone--is that intentional?  Just asking for a friend, https://prx.zendesk.com/agent/tickets/106744.

**Comment by cavis** [comment]
This will be fixed after #443 and publish.prx.org#540, both of which are in this sprint.  (Also adding this issue to the sprint, so i remember to test it).

**Comment by debenedictis** [comment]
@cavis Thank you.

**Comment by cavis** [comment]
Fix deployed to prod!
