### ISSUE TITLE
security patches

### ISSUE THREAD

**Issue by pkarman** [PRX/cms.prx.org#446]
~We need to see why this is breaking!~

![screen shot 2018-08-29 at 2 00 34 pm](https://user-images.githubusercontent.com/1205061/44809295-f1331880-ab93-11e8-859c-3a7bbdf6f7bf.png)

Update: updates in 3 of our rails apps:

- PRX/id.prx.org#110
- PRX/cms.prx.org#451
- PRX/feeder.prx.org#306

Will want to deploy/test ID first, to make sure it doesn't break auth token compatibility with the other apps.  Then deploy CMS and Feeder.

**Comment by cavis** [comment]
Note: these gem upgrades break compatibility with ID.  Need to figure out what else needs to upgrade (and it may be the prx auth gem, not ID itself).
