### ISSUE TITLE
Swap staging Elasticsearch backend

### ISSUE THREAD

**Issue by farski** [PRX/cms.prx.org#502]
Need to switch the ESS deployment that staging is using to hit the [new](https://github.com/PRX/Infrastructure/pull/300) templated version

**Comment by farski** [comment]
https://console.aws.amazon.com/es/home?region=us-east-1#domain:resource=staging-elasti-daiz9fkr255v;action=dashboard

VPC endpoint `https://vpc-staging-elasti-daiz9fkr255v-i5ql5hwamfk2odmcankddfppqm.us-east-1.es.amazonaws.com`

**Comment by cavis** [comment]
Done!
