### ISSUE TITLE
Create the TW Smart Speaker audio segment RSS feed

### ISSUE THREAD

**Issue by brandonhundt** [PRX/cms.prx.org#522]
My preference would be to move this feed off of PRI.org Drupal and use the CMS.prx.org endpoint https://www.pri.org/feed/segmentsworldextra since it only touches audio files.

**Comment by cavis** [comment]
This is around how Google News wants audio - individual subject audio files.

So for a single episode, with multiple segments, we want to allow:

1. Distributing a feed with all the episode audio stitched together (our current feeder/dovetail podcast distribution setup)
2. Distributing a feed with all segments separated, plus some metadata about each segment, as separate `<item>`s

Some questions still about how to group audio_files into "blocks" within an episode.  And distributing blocks.

**Comment by brandonhundt** [comment]
Also, there's an intro file on this feed in the <media:content> attribute. That will play before the enclosure, more of a series level setting.
