### ISSUE TITLE
Overhaul versions

### ISSUE THREAD

**Issue by chrisrhoden** [PRX/cms.prx.org#84]
Versions are getting an overhaul
- All stories have a default "Story" version
- All other versions descend from that version
- All story metadata fields are stored on the version
- Each distribution channel enabled on a story results in a version being added
- All versions have an on/off switch

**Comment by cavis** [comment]
@kookster this has some things in common with #147.  Any thoughts/updates on the scope of this issue?

**Comment by kookster** [comment]
thinking has evolved over the years on this, might be worth revisiting once we start adding additional versions, but that will be after podcast publishing

**Comment by kookster** [comment]
we are putting most of this into the distributions now and not the versions, as the user deciding to override the basic story attributes seems to almost always be related to distributing to a specific platform
