### ISSUE TITLE
Move _links.self.profile  to _links.profile.href

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#88]
The profile should be its own link, not an attribute on the self link.

**Comment by chrisrhoden** [comment]
Would self no longer have a profile attribute?

**Comment by kookster** [comment]
not on the self link - there would be a profile attribute in links to other resources, as there is now.

**Comment by kookster** [comment]
check with @chrisrhoden about if the www app handles this change, can just add the _links.profile.href, but leave the other profile for backwards compatibility if that is the case

**Comment by kookster** [comment]
added proper href, left the `_links.self.profile` for backwards compatibility until www is updated
